### PR TITLE
WIP: Return multiple elements with `:<>` element name.

### PR DESCRIPTION
**Pull request by harryvederci**
I still need to add tests, but before I do that please let me know if this is something you would like to add at all.

### CODE REVIEW

**Comment by swlkr** [comment]
Is this, this? https://github.com/swlkr/janet-html/blob/master/test/janet-html.janet#L39-L43

Or is this at the root level?

**Comment by harryvederci** [comment]
It's similar, but not the same:

```
(test "two non-nested elements without attributes"
  (= `<span>hello world</span><span>2</span>`
     (html/html [:<>
                 [:span "hello world"]
                 [:span "2"]])))

```

**Comment by swlkr** [comment]
ohh I get it, yeah this is cool, I'm just going to assume this passes tests since I don't have janet installed on my computer currently.

**Comment by swlkr** [comment]
Oh wait it was a WIP, dang it! Oh well, not sure if I want to try to undo this, if someone complains or if you want to expand on this we'll handle it then

**Pull request merged**
